- name: Create mountpoints
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  loop: ["/media/1TB", "/media/nvme", "/media/data"]
- name: Update /etc/fstab
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/fstab
    block: |
      /dev/sda5 /media/1TB ntfs-3g defaults,permissions,nofail 0 0
      /dev/nvme0n1p5 /media/nvme ext4 defaults,nofail 0 0
      /dev/sdb1 /media/data ext4 defaults,nofail 0 0
  register: fstab
- name: 'Mount all'
  become: yes
  command: 'mount -a'
  when: fstab.changed
- name: Symlink to Code
  ansible.builtin.file:
    src: /media/data/Rihards/Code
    dest: /home/rihards/Code
    state: link
