- name: Add user.email to ~/.gitconfig
  community.general.git_config:
    name: user.email
    scope: global
    value: rudenspavasaris@proton.me

- name: Add user.name to ~/.gitconfig
  community.general.git_config:
    name: user.name
    scope: global
    value: Rihards

- name: Create .ssh folder
  file:
    path: "/home/{{ user }}/.ssh"
    state: directory

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "/home/{{ user }}/.ssh/id_ed25519"
    type: ed25519

- ansible.builtin.debug:
    msg: lookup('ansible.builtin.file', "/home/{{ user }}/.ssh/id_ed25519")

- ansible.builtin.debug: msg="{{ item }}"
  with_file:
    - "/home/{{ user }}/.ssh/id_ed25519.pub"
