- name: Create applets folder
  become: yes
  file:
    path: "/home/{{ user }}/.local/share/cinnamon/applets"
    state: directory
# https://forums.linuxmint.com/viewtopic.php?t=376881
### Get the PlacesCenter applet
- name: PlacesCenter applet
  become: yes
  ansible.builtin.unarchive:
    src: https://cinnamon-spices.linuxmint.com/files/applets/placesCenter@scollins.zip
    dest: /home/{{ user }}//.local/share/cinnamon/applets
    remote_src: yes

- name: Check that Gsettings were applied. Dirty with a file
  stat:
    path: /home/{{ user }}//.gsettings_script_out
  register: result
- name: Gsettings script
  ansible.builtin.shell: bash ./files/gsettings.sh >> /home/{{ user }}//.gsettings_script_out
  when: not result.stat.exists

- name: Gsettings for stac
  ansible.builtin.shell: |
    gsettings set org.cinnamon.desktop.peripherals.mouse left-handed false
  when: not result.stat.exists

# TODO: VScodium and Firefox need to be started before running these
- name: Check that VSCodium was started once
  stat:
    path: "/home/{{ user }}/.config/VSCodium/User/settings.json"

- name: Open VS Codium first
  ansible.builtin.shell: codium
  when: not result.stat.exists

- name: VSCodium settings
  copy:
    src: "VSCodium/{{ item }}"
    dest: "/home/{{ user }}/.config/VSCodium/User/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - settings.json
    - keybindings.json

- name: Find Firefox user directory
  ansible.builtin.find:
    paths: "/home/{{ user }}/.mozilla/firefox/"
    patterns: '*.default-release'
    recurse: no
    file_type: directory
  register: firefox_setting_folder

- debug:
    var: firefox_setting_folder.files[0].path

- name: Firefox settings
  copy:
    src: "user.js"
    dest: "{{ firefox_setting_folder.files[0].path }}/user.js"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Remove folders
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: absent
  loop:
    - Videos
    - Templates
    - Public
    - Pictures
    - Music
    - Documents

- name: Remove file manager bookmarks
  ansible.builtin.lineinfile:
    path: "/home/{{ user }}/.config/gtk-3.0/bookmarks"
    state: absent
    regexp: "{{ item }}"
  loop:
    - Documents
    - Music
    - Pictures
    - Videos
