- name: Remove packages
  become: yes
  apt:
    pkg:
      - hexchat
      - transmission-*
    state: absent
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    pkg:
### From added repositories
      - signal-desktop
      - brave-browser
#      - kubectl
      - tofu
      - codium
# General
      - vim
      - git
      - chromium
      - audacious
      - vlc
      - keepassxc
      - psensor
      - sysstat
#      - gimp
      - jq
      - gparted


# Get Kubectl directly, as their apt key seemed to be failing recently.
# https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
