- name: Remove packages
  become: yes
  apt:
    pkg:
      - hexchat
      - transmission-*
    state: absent
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    pkg:
      - vim
      - git
      - chromium
      - audacious
      - vlc
      - keepassxc
      - psensor
      - sysstat
#      - kubectl
#      - cri-tools
      - tofu
      - codium
      - brave-browser
#      - gimp
      - jq
      - signal-desktop
      - gparted
