- name: Remove packages
  become: yes
  apt:
    pkg:
      - hexchat
      - transmission-*
    state: absent
- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
- name: Install packages
  become: yes
  apt:
    pkg:
      - vim
      - git
      - chromium
      - audacious
      - vlc
      - keepass2
      - psensor
      - sysstat
      - lutris
      - snapd
      - kubectl
      - cri-tools
      - terraform
- name: Install VS Codium
  community.general.snap:
    name: codium
    classic: true
  become: yes
