- name: Install pip packages
  pip:
    name:
      - jupyterlab
# for dwarfs. Fails so skip that.
      # - cmake
      # - mistletoe
# Add to path
# export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"
