- name: apt keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://apt.releases.hashicorp.com/gpg
    - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    - https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

- name: apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
  loop:
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://apt.releases.hashicorp.com bullseye main"
    - "deb https://download.vscodium.com/debs vscodium main"
    - "deb https://brave-browser-apt-release.s3.brave.com/ stable main"

- name: Containerd CRI plugin was disabled by default, but enable it by commenting
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins'
    line: '#disabled_plugins'