- name: Add VSCodium repo
  ansible.builtin.deb822_repository:
    name: VSCodium
    types: deb
    uris: https://download.vscodium.com/debs
    suites: 'vscodium'
    components: main
    architectures: amd64
    signed_by: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: Add OpenTofu repo
  ansible.builtin.deb822_repository:
    name: OpenTofu
    types: deb
    uris: https://packages.opentofu.org/opentofu/tofu/any/
    suites: any
    components: main
    architectures: amd64
#    signed_by: https://get.opentofu.org/opentofu.gpg
    signed_by: https://packages.opentofu.org/opentofu/tofu/gpgkey

- name: Add Brave repo
  ansible.builtin.deb822_repository:
    name: Brave
    types: deb
    uris: https://brave-browser-apt-release.s3.brave.com/
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

- name: Add Signal repo
  ansible.builtin.deb822_repository:
    name: Signalll
    types: deb
    uris: https://updates.signal.org/desktop/apt
    suites: xenial
    components: main
    architectures: amd64
    signed_by: https://updates.signal.org/desktop/apt/keys.asc

### Kubernetes key fails to download
#- name: Add Kubernetes repo
#  deb822_repository:
#    name: Kubernetes
#    types: deb
#    uris: https://pkgs.k8s.io/core:/stable:/v1.36/deb/
#    suites: /
#    architectures: amd64
#    signed_by: https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key
