- name: Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    update_cache: true

- name: Terraform apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
- name: Terraform repository
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com bullseye main"
    state: present
    update_cache: true
