- name: Install packages
  become: yes
  apt:
    update_cache: yes
    pkg:
      - lutris
      - gimp
      - kdenlive
      - handbrake
      - iw # for the wifi adapter

- name: Create place for containerd storage
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  loop: ["/media/ssd/containerd", "/data"]

- name: Symlink to containerd storage
  ansible.builtin.file:
    src: /media/ssd/containerd
    dest: /data/containerd
    state: link

- include_tasks: ../tasks/containerd.yml
