- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  vars:
    user: rihards
  tasks:
  - name: Do the admin tasks
    become: yes
    block:
    - include_tasks: ./tasks/laptop_disks.yml
    - include_tasks: ./tasks/packages.yml
  - include_tasks: ./tasks/gsettings.yml
  - name: Remove folders
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /home/rihards/Videos
      - /home/rihards/Templates
      - /home/rihards/Public
      - /home/rihards/Pictures
      - /home/rihards/Music
      - /home/rihards/Documents
  - name: git email
    community.general.git_config:
      name: user.email
      scope: global
      value: rudenspavasaris@proton.me
  - name: git username
    community.general.git_config:
      name: user.name
      scope: global
      value: Rihards
  - name: git username
    community.general.git_config:
      name: core.editor
      scope: global
      value: vim
  - name: ACPI error workaround with cron on reboot
    become: yes
    ansible.builtin.cron:
      name: "ACPI workaround on reboot"
      special_time: reboot
      # job: /bin/bash for F in $(awk '$4=="unmasked"&&$1>1000{print FILENAME}' /sys/firmware/acpi/interrupts/*); do tee $F <<<mask; done
      job: /usr/bin/echo "mask" > /sys/firmware/acpi/interrupts/gpe16
      user: root
      cron_file: acpi_workaround
