---
- hosts: all
  remote_user: rihards
  become: yes
  become_user: root
  become_method: sudo
  vars:
    repo_path: # variable refered to in task with_items
      - /srv/
  tasks:
    # - git:
    #     repo: 'git@gitlab.com:RihardsT/cloud_project_infrastructure.git'
    #     dest: {{ repo_path }}
    #     accept_hostkey: yes
    #     depth: 1
        # key_file: /var/
      # with_items: "{{ repo_path }}"

    # - docker_service: # https://docs.ansible.com/ansible/docker_service_module.html
    #     project_src: /srv/
    #     state: absent
    - copy:
        src: ../Secrets/ip_change_telegram.sh
        dest: /root/ip_change_telegram.sh
        owner: root
        group: root
        mode: 0700

    - cron:
        name: "ip_change_notify_telegram"
        minute: "*/1"
        user: root
        # cron_file: /etc/cron.hourly/ip_change_notify_telegram
        job: "/bin/bash /root/ip_change_telegram.sh"
