---
- hosts: aws
  become: yes
  become_user: root
  become_method: sudo
  vars:
    fail2ban_bantime: 604800
    fail2ban_maxretry: 2
    fail2ban_services:
      - name: sshd
        port: 22
        bantime: 604800
        maxretry: 2
    security_ssh_port: 22
    app_user: rihards #
    docker_group_members: [rihards]
  roles:
    - common # User setup, set up auth stuff and clone repository
    - geerlingguy.security
    - tersmitten.fail2ban
    - { role: angstwad.docker_ubuntu, when: ansible_architecture == 'x86_64' }
