- name: Bring up services
  hosts: production
  vars:
    repo_path: /var/www/dok.rudenspavasaris.id.lv/
  tasks:
    - name: Pip install mkdocs and cinder theme
      pip:
        name: mkdocs,mkdocs-cinder
        state: latest
      become: yes
      become_user: root # This pip install requires root

    - name: Clone/update the git repo
      git:
        repo: 'git@gitlab.com:RihardsT/cloud_project_documentation.git'
        dest: '{{ repo_path }}'
        depth: 1
        update: yes
        accept_hostkey: yes
        key_file: /home/{{ ansible_user }}/.ssh/for_clone
      register: git

    # This need many imporements. As it's not working correctly.
    - name: Run mkdocs build
      command: mkdocs build
      args:
        chdir: '{{ repo_path }}'
      when: git.changed # Add when statement, to only do these steps when new changes have pulled from git.

    - name: Restart Nginx service
      docker_service: # https://docs.ansible.com/ansible/docker_service_module.html
        project_src: "/srv/repo/DockerGunicornARM/"
        restarted: true
        state: present
        services: nginx
      when: git.changed # Add when statement, to only do these steps when new changes have pulled from git.