---
- name: Base setup - User setup, fail2ban, security.
  hosts: production
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: [rihards]
    app_user_groups:
    security_ssh_port: 3013
    security_sudoers_passwordless: [rihards]
    kubernetes_role: master
    kubernetes_version: '1.24'
    kubernetes_kubelet_extra_args: "--fail-swap-on=false"
    # move that to /var/lib/kubelet/kubeadm-flags.env # failSwapOn: false
    kubernetes_ignore_preflight_errors: "all"
    kubernetes_pod_network_cidr: "10.244.0.0/16"
    kubernetes_allow_pods_on_master: True
    kubernetes_apiserver_advertise_address: "95.216.206.226"
    kubernetes_kubeadm_init_extra_opts: "--apiserver-cert-extra-sans rudenspavasaris.id.lv"
  vars_files:
    - vars/app_user.yml
  pre_tasks:
    - include_tasks: ./tasks/app_user.yml
    - include_tasks: ./tasks/s3cfg.yml
    - include_tasks: ./tasks/containerd.yml
    - include_tasks: ./tasks/keep_clean.yml
  roles:
    - geerlingguy.security
    - geerlingguy.kubernetes
