---
- name: Base setup - User setup, fail2ban, security.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: rihards
    security_ssh_port: 3013
    security_sudoers_passwordless: [rihards]
    docker_users: [rihards]
    docker_apt_arch: amd64
    kubernetes_role: node
    kubernetes_version: '1.15'
    kubernetes_kubelet_extra_args: "--fail-swap-on=false"
    kubernetes_ignore_preflight_errors: "all"
    kubernetes_join_command: "kubeadm join 95.216.206.226:6443 --token kk4z8h.bmx2khs7jqmc1qwq --discovery-token-ca-cert-hash sha256:3c458c230ff5ef3f7fa9d21a1cd408b8f9e19b82b3aa103121cd610f715d3950 --ignore-preflight-errors=all"
  pre_tasks:
    - name: Create app_user
      user:
        name: "{{ item }}"
        shell: /bin/bash
        generate_ssh_key: no
      with_items: "{{ app_user }}"
    - name: Copy SSH key
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '../Secrets/SSH_Keys/ssh_key.pub') }}"
      with_items: "{{ app_user }}"
  roles:
    - geerlingguy.security
    - geerlingguy.docker
    - geerlingguy.kubernetes
  tasks:
    - name: Upgrade packages
      apt:
        upgrade: yes
        update_cache: yes
