---
- name: Base setup - User setup, fail2ban, security.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: [rihards]
    # security_ssh_port: 3013
    security_sudoers_passwordless: [rihards]
  pre_tasks:
    - include: ./tasks/app_user.yml
    - include: ./tasks/s3cfg.yml
    - include: ./tasks/podman.yml
    - include: ./tasks/restore_minecraft.yml
  roles:
    - geerlingguy.security
  tasks:
    - name: Create Minecraft server
      containers.podman.podman_container:
        name: minecraft
        image: docker.io/itzg/minecraft-server
        state: started
        env:
          EULA: "true"
          MEMORY: "4G"
        volumes:
          /data/minecraft_data:/data
        publish:
          - '25565:25565'
