---
- name: Base setup - User setup, fail2ban, security.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    fail2ban_bantime: 604800
    fail2ban_maxretry: 2
    fail2ban_services:
      - name: sshd
        port: 22
        bantime: 604800
        maxretry: 2
    security_ssh_port: 22
    app_user: rihards #
    repo_path: /srv/repo
    docs_path: /var/www/dok.rudenspavasaris.id.lv/
    docker_group_members: [rihards]
  vars_files:
    - vars/gitlab_runner.yml
    - vars/vault.yml
  roles:
    - common # User setup, set up auth stuff and clone repository
    - geerlingguy.security
    - tersmitten.fail2ban
    - { role: angstwad.docker_ubuntu, when: ansible_architecture == 'x86_64' }
    - dblaci.ansible-gitlab-runner
    - docker_services
    - docs_page
  tasks:
  #   - name: Reload sshd service to load updated security settings
  #     service: name=sshd state=reloaded
    - name: Set up cron to trigger nightly docker image build job
      cron:
        name: "Trigger Gitlab CI docker image build job"
        minute: 0
        hour: 0
        user: root
        job: "curl -X POST -F token={{ gitlab_pipeline_token }} -F ref=master {{ gitlab_pipeline_url }}"
        state: present