---
- name: Base setup - User setup, fail2ban, security.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    fail2ban_services:
      - name: sshd
        port: 22
        bantime: 3600
    security_ssh_port: 22
    app_user: rihards #
    repo_path: /srv/repo
    docs_path: /var/www/dok.rudenspavasaris.id.lv/
  roles:
    - common # User setup, set up auth stuff and clone repository
    - geerlingguy.security
    - tersmitten.fail2ban
    - { role: angstwad.docker_ubuntu, when: ansible_architecture == 'x86_64' }
  # tasks:
  #   - name: Reload sshd service to load updated security settings
  #     service: name=sshd state=reloaded

- name: Bring up services
  hosts: production
  become: yes
  become_user: rihards
  roles:
    - docker_services
    - docs_page