---
- name: Base setup - User setup, fail2ban, security.
  hosts: production
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: rihards
    security_ssh_port: 3013
    security_sudoers_passwordless: [rihards]
    docker_users: [rihards]
    docker_apt_arch: amd64
    kubernetes_role: master
    kubernetes_version: '1.14'
    kubernetes_kubelet_extra_args: "--fail-swap-on=false"
    kubernetes_ignore_preflight_errors: "all"
    kubernetes_pod_network_cidr: "10.244.0.0/16"
    kubernetes_allow_pods_on_master: True
    kubernetes_apiserver_advertise_address: "163.172.162.100"
    kubernetes_kubeadm_init_extra_opts: "--apiserver-cert-extra-sans rudenspavasaris.id.lv"
  vars_files:
    - vars/gitlab_runner.yml
    - vars/vault.yml
  roles:
    - common # User setup, set up auth stuff
    - geerlingguy.security
    - geerlingguy.docker
    - geerlingguy.kubernetes
  # tasks:
  #   - name: Reload sshd service to load updated security settings
  #     service: name=sshd state=reloaded
