---
- name: Base setup - User setup, fail2ban, security.
  hosts: raspberry
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: rihards
    security_ssh_port: 3471
    security_sudoers_passwordless: [rihards]
  roles:
    - common # User setup, set up auth stuff and clone repository
    - geerlingguy.security
  tasks:
    - name: Remove python-pip
      apt:
        name: python-pip
        state: absent
    - name: Install python3-pip
      apt:
        name: python3-pip
        update_cache: yes
    - pip:
        name:
          - picamera
          - rpi.gpio



  #   # Set up IP change notification to telegram
  #   - name: Copy IP check script, that notifies to telegram
  #     copy:
  #       src: ../Secrets/ip_change_telegram.sh
  #       dest: /root/ip_change_telegram.sh
  #       owner: root
  #       group: root
  #       mode: 0700
  #   - name: set up cronjob to notify of IP change
  #     cron:
  #       name: "ip_change_notify_telegram"
  #       minute: "*/30"
  #       user: root
  #       # cron_file: /etc/cron.hourly/ip_change_notify_telegram
  #       job: "/bin/bash /root/ip_change_telegram.sh"
