---
- name: Base setup - User setup, fail2ban, security.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: rihards
    # security_ssh_port: 3471
    security_sudoers_passwordless: [rihards]
  pre_tasks:
    - include: ./tasks/app_user.yml
  roles:
    - geerlingguy.security
  tasks:
    - name: Remove python-pip
      apt:
        name: python-pip
        state: absent
    - name: Install python3-pip
      apt:
        name:
          - python3-pip
          - libraspberrypi-bin
        update_cache: yes
    - pip:
        executable: pip3
        name:
          - picamera
          - rpi.gpio
          - opencv
