---
- name: Base setup - User setup, fail2ban, security.
  hosts: raspberry
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: rihards
    security_ssh_port: 3471
    security_sudoers_passwordless: [rihards]
  roles:
    - common # User setup, set up auth stuff and clone repository
    - geerlingguy.security
  tasks:
    - name: Remove python-pip
      apt:
        name: python-pip
        state: absent
    - name: Install python3-pip
      apt:
        name: python3-pip
        update_cache: yes
    - pip:
        name:
          - picamera
          - rpi.gpio
