---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    repo_path: /srv/repo
  tasks:
    # Set up IP change notification to telegram
    - name: Copy IP check script, that notifies to telegram
      copy:
        src: ../Secrets/ip_change_telegram.sh
        dest: /root/ip_change_telegram.sh
        owner: root
        group: root
        mode: 0700
    - name: set up cronjob to notify of IP change
      cron:
        name: "ip_change_notify_telegram"
        minute: "*/30"
        user: root
        # cron_file: /etc/cron.hourly/ip_change_notify_telegram
        job: "/bin/bash /root/ip_change_telegram.sh"

    # Docker compose service stuff
    - command: "uname -m"
      register: architecture

    - name: Docker compose up. Bring up the services
      docker_service: # https://docs.ansible.com/ansible/docker_service_module.html
        project_src: "/srv/repo/DockerGunicornARM/"
        state: present
        services: netdata
        files: docker-compose_{{ architecture.stdout }}.yml