---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    repo_path: /srv/repo
  tasks:
    # Set up IP change notification to telegram
    - name: Copy IP check script, that notifies to telegram
      copy:
        src: ../Secrets/ip_change_telegram.sh
        dest: /root/ip_change_telegram.sh
        owner: root
        group: root
        mode: 0700
    - name: set up cronjob to notify of IP change
      cron:
        name: "ip_change_notify_telegram"
        minute: "*/30"
        user: root
        # cron_file: /etc/cron.hourly/ip_change_notify_telegram
        job: "/bin/bash /root/ip_change_telegram.sh"

    # Project dependency setup
    - copy:
        src: ../Secrets/SSH_Keys/for_clone
        dest: /home/rihards/.ssh/for_clone
        owner: rihards
        group: rihards
        mode: 0700

    - git:
        repo: 'git@gitlab.com:RihardsT/cloud_project_infrastructure.git'
        dest: "{{ repo_path }}"
        depth: 1
        update: yes
        accept_hostkey: yes
        key_file: /home/rihards/.ssh/for_clone

    # - pip:
    #     name: docker-compose
    #     state: latest
    - name: Create .docker directory
      file: path=/root/.docker state=directory # Nice example of "single line"

    - name: Copy Docker auth
      copy:
        src: ../Secrets/Docker_auth.json
        dest: /root/.docker/config.json
        owner: root
        group: root
        mode: 0500

    # Docker compose service stuff
    - name: Docker compose up. Bring up the services
      docker_service: # https://docs.ansible.com/ansible/docker_service_module.html
        project_src: "/srv/repo/DockerGunicornARM/"
        state: present
        services: netdata