---
- name: Base setup - User setup, fail2ban, security.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    app_user: rihards
    security_sudoers_passwordless: [rihards]
    app_user_groups: video,gpio # pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi
  vars_files:
    - vars/app_user.yml
  pre_tasks:
    - include: ./tasks/app_user.yml
    - include: ./tasks/containerd.yml
  roles:
    - geerlingguy.security
  tasks:
    - name: Install python3-pip
      apt:
        name:
          - python3-pip
          # - libraspberrypi-bin
        update_cache: yes
    # - pip:
    #     executable: pip3
    #     name:
    #       - rpi.gpio
    #       - opencv
