# Install a roles from the Ansible Galaxy
- src: geerlingguy.security
- src: geerlingguy.docker
- src: geerlingguy.kubernetes

# From GitHub
# - name: dblaci.ansible-gitlab-runner
#   src: https://github.com/DBLaci/ansible-gitlab-runner
