- name: Create a .kube directory
  file:
    path: "/home/{{ item }}/.kube"
    state: directory
    owner: "{{ item }}"
  with_items: "{{ app_user }}"
- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ item }}/.kube/config"
    remote_src: yes
    mode: 0644
    owner: "{{ item }}"
  with_items: "{{ app_user }}"
- name: Copy kubeconfig to local
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes
# Replace this below with K8s task? Don't want to install a module currently
- name: Set up K8s services (Longhorn, Traefik)
  become_user: rihards
  delegate_to: localhost
  ansible.builtin.command: "kubectl apply -f {{ item }}"
  loop:
   - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
   - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
   - ~/Code/cloud_project/cloud_project_kubernetes/Traefik_v2/
   - https://raw.githubusercontent.com/longhorn/longhorn/v1.4.0/deploy/longhorn.yaml
