# Seems like this didn't help anyway with the Nextcloud AIO too many open files issue
# sudo sysctl -w fs.nr_open=1048576 # The value it had
# sudo sysctl -w fs.nr_open=91048576
- sysctl:
    name: fs.nr_open
    value: '91048576'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/98-fs-nr-open.conf
    reload: yes

- name: Create a .kube directory
  file:
    path: "/home/{{ item }}/.kube"
    state: directory
    owner: "{{ item }}"
  with_items: "{{ app_user }}"
- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ item }}/.kube/config"
    remote_src: yes
    mode: 0600
    owner: "{{ item }}"
  with_items: "{{ app_user }}"
- name: Copy kubeconfig to local
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes
# Replace this below with K8s task? Don't want to install a module currently
- name: Set up K8s services (Longhorn, Traefik)
  become_user: rihards
  delegate_to: localhost
  ansible.builtin.command: "kubectl apply -f {{ item }}"
  loop:
    - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
    - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
    - ~/Code/cloud_project/cloud_project_kubernetes/Base/Traefik_v2/
    - https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
    - ~/Code/cloud_project/cloud_project_kubernetes/CI_CD_IaC_Tools/ArgoCD/namespace.yaml
    - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml -n argocd
    - ~/Code/cloud_project/cloud_project_kubernetes/CI_CD_IaC_Tools/ArgoCD/argo_config.yaml
