- name: Add some aliases on node
  copy:
    dest: "/home/{{ user }}/.bash_aliases"
    content: |
      alias nerk="sudo nerdctl -n k8s.io"
      alias nerdctl="sudo nerdctl"
      alias dfsda1="df -h /dev/sda1"
      alias aptupgr="sudo apt update; sudo apt upgrade"

- name: Autocompletions
  become: yes
  ansible.builtin.blockinfile:
    path: "/home/{{ user }}/.bashrc"
    block: |
      source <(/usr/local/bin/nerdctl completion bash)
      source <(kubectl completion bash)
