# Remember to have: source ~/.bash_aliases
# in ~/.bashrc or such

- name: Touch again the same file, but do not change times this makes the task idempotent
  ansible.builtin.file:
    path: ~/.bash_aliases
    state: touch
    mode: u+rw,g-wx,o-rwx
    modification_time: preserve
    access_time: preserve

- name: Check if alias markers exist
  when: cloud == "oracle"
  become_user: rihards
  delegate_to: localhost
  ansible.builtin.lineinfile:
    dest: ~/.bash_aliases
    line: "#OCI_ALIASES"
  check_mode: yes
  register: alias_markers
# - debug: var=alias_markers.changed

- name: Add markers for aliases locally
  when: cloud == "oracle" and alias_markers.changed
  become_user: rihards
  delegate_to: localhost
  ansible.builtin.blockinfile:
    path: "~/.bash_aliases"
    block: |
      #OCI_ALIASES
      #END_OCI_ALIASES

- name: Add some aliases locally
  when: cloud == "oracle" # And potentially add variable to check it's run from Terraform
  become_user: rihards
  delegate_to: localhost
  ansible.builtin.shell: |
    OUTPUT_IP_1=$(tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ output -raw ip)
    
    ex ~/.bash_aliases << EOF
    /#OCI_ALIASES/,/#END_OCI_ALIASES/c
    #OCI_ALIASES
    alias local_alias_update="ansible-playbook ~/Code/cloud_project/cloud_project_ansible/LinuxMint_setup/aliases_only.yaml"
    alias oc1_tf="tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ apply"
    # SSH
    alias oc1_ssh="ssh ${OUTPUT_IP_1} -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null'"
    # alias oc2_ssh="ssh -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null' -A -J ${OUTPUT_IP_1} $(tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ output -raw ip_2)"
    # alias oc3_ssh="ssh -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null' -A -J ${OUTPUT_IP_1} $(tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ output -raw ip_3)"
    
    ########## Ansible
    alias oc1_ansible="ansible-playbook -i ${OUTPUT_IP_1}, \
      -e node_ip_address=${OUTPUT_IP_1} \
      -u ubuntu --diff -e ansible_python_interpreter=/usr/bin/python3 -e ansible_port=22 \
      /home/rihards/Code/cloud_project/cloud_project_ansible/oc1.yml"
    ##### OC2
    # alias oc2_ansible="ansible-playbook -i $(tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ output -raw ip_2), \
    #   -e node_ip_address=$(tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ output -raw ip_2) \
    #   --ssh-common-args=\"-A -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null' -o ProxyCommand='ssh -W %h:22 -q ${OUTPUT_IP_1}'\" \
    #   -u ubuntu --diff -e ansible_python_interpreter=/usr/bin/python3 -e ansible_port=22 \
    #   /home/rihards/Code/cloud_project/cloud_project_ansible/oc0.yml"
    ##### OC3
    # alias oc3_ansible="ansible-playbook -i $(tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ output -raw ip_3), \
    #   -e node_ip_address=$(tofu -chdir=/home/rihards/Code/cloud_project/cloud_project_terraform_oracle/ output -raw ip_3) \
    #   --ssh-common-args=\"-A -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null' -o ProxyCommand='ssh -W %h:22 -q ${OUTPUT_IP_1}'\" \
    #   -u ubuntu --diff -e ansible_python_interpreter=/usr/bin/python3 -e ansible_port=22 \
    #   /home/rihards/Code/cloud_project/cloud_project_ansible/oc0.yml"
    #END_OCI_ALIASES
    .
    w!
    q
    EOF
