- name: Create app_user
  user:
    name: "{{ item }}"
    shell: /bin/bash
    generate_ssh_key: no
    password: "{{ app_user_password }}"
    groups: "{{ app_user_groups }}"
    append: yes
  with_items: "{{ app_user }}"
- name: Copy SSH key
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/home/rihards/.ssh/id_ed25519.pub') }}"
  with_items: "{{ app_user }}"
- name: Upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
- name: Install jq
  apt:
    pkg:
      - jq
