- name: Create app_user
  user:
    name: "{{ user }}"
    shell: /bin/bash
    generate_ssh_key: no
    password: "{{ app_user_password }}"
    groups: "{{ app_user_groups }}"
    append: yes

- name: Copy SSH key
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ lookup('file', '/home/rihards/.ssh/id_ed25519.pub') }}"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+6+zyGdusVLIsx+nnqo4/3qeylb8aFBmCS2wolK3kB"

- name: Upgrade packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install jq
  apt:
    pkg:
      - jq
      - net-tools
# TODO: Copy private SSH key too, for Gitlab
