##### Containerd
- modprobe:
    name: overlay
    state: present
- modprobe:
    name: br_netfilter
    state: present
- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
- sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
- sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
- name: containerd conf
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
- name: containerd
  apt:
    pkg:
      - containerd
- name: Create a data directory
  file:
    path: /etc/containerd
    state: directory
- name: Check that /etc/containerd/config.toml exists
  stat:
    path: /etc/containerd/config.toml
  register: result
- name: containerd config default
  shell: |
    containerd config default | tee /etc/containerd/config.toml
  when: not result.stat.exists
- name: Create ContainerD directory for GCP
  file:
    path: "/data/containerd"
    state: directory
    mode: '0755'
- name: Containerd root storage
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^root ='
    line: 'root = "/data/containerd"'
  register: result
- name: Containerd CRI plugin was disabled by default, but enable it by commenting
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins'
    line: '#disabled_plugins'
  register: result
- name: Add sockets to crictl
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
- name: Restart containerd after root storage change
  service:
    name: containerd
    state: restarted
  when: result is changed
- name: CNI plugin directory
  file:
    path: "{{ item }}"
    state: directory
  with_items: ["/cni_plugins", "/opt/cni/bin"]
- name: nerdctl
  ansible.builtin.unarchive:
    src: https://github.com/containerd/nerdctl/releases/download/v1.0.0/nerdctl-1.0.0-linux-amd64.tar.gz
    include: nerdctl
    dest: /usr/local/bin
    remote_src: yes
- name: Get CNI plugins
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    # include: bridge # This one breaks this one for some reason
    dest: /cni_plugins
    remote_src: yes
- name: Move CNI plugins
  ansible.builtin.copy:
    src: "/cni_plugins/{{ item }}"
    dest: /opt/cni/bin
    remote_src: yes
    mode: '0775'
  with_items: ["bridge", "portmap", "firewall", "tuning", "host-local"]
  notify: restart_containerd
