# Found that dummy IP is required for Oracle Cloud and GCP.
# In general for nodes, that do not have public IP anywhere in their interfaces
# ifconfig or ip addr
- name: Check that dummy_ip exists
  stat:
    path: /dummy_ip
  register: dummy_ip
- modprobe:
    name: dummy
    state: present
- name: Add dummy IP
  shell: |
    lsmod | grep dummy
    ip link add eth0 type dummy
    ip addr add {{ node_ip_address }}/24 brd + dev eth0 label eth0:0
    touch /dummy_ip
  when: not dummy_ip.stat.exists
