- name: Journalctl SystemMaxUse
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse='
    line: 'SystemMaxUse=100M'
# Set up a cronjob to remove old Kubernetes backup files
# ls -t /etc/kubernetes/tmp | sed -e '1,4d' | xargs -I % rm -rf '/etc/kubernetes/tmp/%'
