- name: kubeadm join config
  ansible.builtin.copy:
    dest: /data/kubeadm_join.yaml
    content: |
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: JoinConfiguration
      discovery:
        bootstrapToken:
          apiServerEndpoint: {{ kubeadm_join_apiServerEndpoint }}
          token: {{ kubeadm_join_token }}
          caCertHashes: {{ kubeadm_join_caCertHashes }}
      nodeRegistration:
        taints:
          - key: "oc0"
            value: "true"
            effect: "NoSchedule"
