- ansible.builtin.iptables:
    chain: INPUT
    rule_num: 6
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
- ansible.builtin.iptables:
    chain: INPUT
    rule_num: 6
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
- ansible.builtin.iptables:
    chain: INPUT
    rule_num: 6
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 6443
    jump: ACCEPT
- ansible.builtin.iptables:
    chain: INPUT
    rule_num: 6
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 10250
    jump: ACCEPT
  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT
  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT
  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 6443 -j ACCEPT
  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 10250 -j ACCEPT
  # sudo netfilter-persistent save
