- ansible.builtin.iptables:
    chain: INPUT
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    action: insert # this is required together with rule_num
    rule_num: 6
- ansible.builtin.iptables:
    chain: INPUT
    rule_num: 6
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    action: insert
- ansible.builtin.iptables:
    chain: INPUT
    rule_num: 6
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 6443
    jump: ACCEPT
    action: insert
- ansible.builtin.iptables:
    chain: INPUT
    rule_num: 6
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: 10250
    jump: ACCEPT
    action: insert
### Very important!
# Delete REJECT rule in FORWARD, because FLANNEL-FWD is created at the end,
# thus blocking Flannel and everything.
# This could be added after K8s resources are applied
- ansible.builtin.iptables:
    chain: FORWARD
    jump: REJECT
    reject_with: icmp-host-prohibited
    state: absent

  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT
  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT
  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 6443 -j ACCEPT
  # sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 10250 -j ACCEPT
  # sudo netfilter-persistent save

# TODO: With the reject rules Longhorn doesn't work on K8s. Investigate it more
# Option to get list of commands to remove all REJECT rules
# sudo iptables-save > iptables_save; cat iptables_save | grep REJECT | sed 's/-A/sudo iptables -D/g'
