- name: Check that /data/minecraft_data exists
  stat:
    path: /data/minecraft_data
  register: result
- name: Restore Minecraft
  shell: |
    backup_timestamp=$(s3cmd ls s3://rudenspavasaris/minecraft | awk '{print $4}' | grep -oP "(?<=minecraft_).*(?=.tar)" | sort | tail -n 1)
    s3cmd get s3://rudenspavasaris/minecraft_${backup_timestamp}.tar
    sudo tar -xzf "minecraft_${backup_timestamp}.tar" -C /
  when: not result.stat.exists
- name: Backup script
  copy:
    src: /home/rihards/Code/cloud_project/cloud_project_ansible/files/minecraft_backup.sh
    dest: /data/minecraft_backup.sh
    mode: 0755
    owner: rihards
- name: Pull Minecraft image
  shell: |
    ctr image pull docker.io/itzg/minecraft-server:latest
