- name: Install pip and utilities
  apt:
    pkg:
      - python3-pip
      - net-tools
      - locate
      - s3cmd
- name: s3cfg
  copy:
    src: "/home/rihards/Code/cloud_project/cloud_project_ansible/files/s3cfg_{{ cloud }}"
    dest: "{{ item }}"
    owner: rihards
    group: rihards
    mode: '0600'
  loop:
    - /home/rihards/.s3cfg
    - /root/.s3cfg
  no_log: True
- name: Create a data directory
  file:
    path: "{{ item }}"
    owner: rihards
    state: directory
    mode: '0775'
  loop:
    - /data/
    - /backups/
