# TCP Iptables
- ansible.builtin.iptables:
    chain: INPUT
    match: state
    ctstate: NEW
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert # this is required together with rule_num
    rule_num: 3
  with_items: [80,81,443,6443,8000,10250,10256,25565,8285,8472,8132,8081]
  # 81 - Potentially for ACME challenge
  # 6443 traefik https
  # 8000 traefik http
  # 10250 - Kubelet API, required to see logs
  # 25565 - Minecraft
  # 8285,8472 - For flannel, but didn't make k8s work with private subnet nodes
  # 8132 - for k0s - konnectivity, https://docs.k0sproject.io/stable/networking/
  # without it allowed, kubectl logs gives "No agent available" error
  # 8081 for k8s, Traefik
- ansible.builtin.iptables:
    chain: INPUT
    match: state
    ctstate: NEW
    protocol: udp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
    rule_num: 6
  with_items: [25565,8285,8472]
# NAT instance
- ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: enp0s6
    jump: MASQUERADE
- ansible.builtin.iptables:
    # table: filter # filter is default
    chain: FORWARD
    out_interface: enp0s6
    jump: ACCEPT
### Very important!
# Delete REJECT rule in FORWARD, because FLANNEL-FWD is created at the end,
# thus blocking Flannel and everything.
# This could be added after K8s resources are applied
- ansible.builtin.iptables:
    chain: FORWARD
    jump: REJECT
    reject_with: icmp-host-prohibited
    state: absent
  # Option to get list of commands to remove all REJECT rules, but not needed
  # sudo iptables-save > iptables_save; cat iptables_save | grep REJECT | sed 's/-A/sudo iptables -D/g'
