- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  vars_files:
    - vars/disks.yml
  handlers:
    - import_tasks: ../handlers/containerd.yml
  tasks:
  - name: Do the admin tasks
    become: yes
    block:
    - include: ./tasks/laptop_disks.yml
    - include: ./tasks/repositories.yml
    - include: ./tasks/packages.yml
    - include: ../tasks/containerd.yml
    - include: ./tasks/gsettings.yml
    - include: ./tasks/pip.yml
  - name: Remove folders
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /home/rihards/Videos
      - /home/rihards/Templates
      - /home/rihards/Public
      - /home/rihards/Pictures
      - /home/rihards/Music
      - /home/rihards/Documents
  - name: Generate SSH key
    community.crypto.openssh_keypair:
      path: /home/rihards/.ssh/id_ed25519
      type: ed25519
      # comment: rhp
  - name: git email
    community.general.git_config:
      name: user.email
      scope: global
      value: rudenspavasaris@proton.me
  - name: git username
    community.general.git_config:
      name: user.name
      scope: global
      value: Rihards
  - name: git username
    community.general.git_config:
      name: core.editor
      scope: global
      value: vim

## for F in $(awk '$4=="unmasked"&&$1>1000{print FILENAME}' /sys/firmware/acpi/interrupts/*); do sudo tee $F <<<mask; done