- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  vars_files:
    - vars/disks.yml
  vars:
    disk_uuid_1TB: "{{ ansible_facts['devices']['sdb']['partitions']['sdb5']['uuid']
      if ansible_facts['devices']['sdb']['partitions']|length == 2
      else
      ansible_facts['devices']['sda']['partitions']['sda5']['uuid'] }}"
    disk_uuid_ssd: "{{ ansible_facts['devices']['sda']['partitions']['sda1']['uuid']
      if ansible_facts['devices']['sda']['partitions']|length == 1
      else
      ansible_facts['devices']['sdb']['partitions']['sdb1']['uuid'] }}"
  handlers:
    - import_tasks: ../handlers/containerd.yml
  tasks:
  - name: "Include global default vars"
    ansible.builtin.include_vars: ../../group_vars/all.yml
  - name: Do the admin tasks
    become: yes
    block:
    - include_tasks: ./tasks/disks.yml
    - include_tasks: ./tasks/repositories.yml
    - include_tasks: ./tasks/packages.yml
    - include_tasks: ./tasks/stac_packages.yaml
  - include_tasks: ./tasks/gsettings.yml
  - include_tasks: ./tasks/aliases.yaml
  - name: Upgrade packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
  - include_tasks: ./tasks/stac_wifi_adapter.yaml
  - include_tasks: ./tasks/git_stuff.yaml
