- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  vars:
    disk_uuid_1TB: "{{ ansible_facts['devices']['sdb']['partitions']['sdb1']['uuid']
      if ansible_facts['devices']['sdb']['size'][:-3] | int > 900
      else
      ansible_facts['devices']['sda']['partitions']['sda1']['uuid'] }}"
    disk_uuid_ssd: "{{ ansible_facts['devices']['sda']['partitions']['sda1']['uuid']
      if ansible_facts['devices']['sda']['size'][:-3] | int < 500
      else
      ansible_facts['devices']['sdb']['partitions']['sdb1']['uuid'] }}"
  vars_files:
    - ../group_vars/all.yml
  handlers:
    - import_tasks: ../handlers/containerd.yml
  tasks:
  - name: Do the admin tasks
    become: yes
    block:
    - include_tasks: ./tasks/disks.yml
    - include_tasks: ./tasks/repositories.yml
    - include_tasks: ./tasks/packages.yml
    - include_tasks: ./tasks/stac_packages.yaml
  - include_tasks: ./tasks/gsettings.yml
  - include_tasks: ./tasks/aliases.yaml
  - name: Upgrade packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
  - include_tasks: ./tasks/stac_wifi_adapter.yaml
  - include_tasks: ./tasks/git_stuff.yaml
