- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  vars_files:
    - vars/disks.yml
  vars:
    user: rihards
    disk_uuid_1TB: "{{ ansible_facts['devices']['sdb']['partitions']['sdb5']['uuid']
      if ansible_facts['devices']['sdb']['partitions']|length == 2
      else
      ansible_facts['devices']['sda']['partitions']['sda5']['uuid'] }}"
    disk_uuid_ssd: "{{ ansible_facts['devices']['sda']['partitions']['sda1']['uuid']
      if ansible_facts['devices']['sda']['partitions']|length == 1
      else
      ansible_facts['devices']['sdb']['partitions']['sdb1']['uuid'] }}"
  handlers:
    - import_tasks: ../handlers/containerd.yml
  tasks:
  - name: Do the admin tasks
    become: yes
    block:
    - include: ./tasks/disks.yml
    - include: ./tasks/repositories.yml
    - include: ./tasks/packages.yml
  - include: ./tasks/gsettings.yml
  - name: Remove folders
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /home/rihards/Videos
      - /home/rihards/Templates
      - /home/rihards/Public
      - /home/rihards/Pictures
      - /home/rihards/Music
      - /home/rihards/Documents
  - name: Upgrade packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
