- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  vars_files:
    - vars/disks.yml
  handlers:
    - import_tasks: ../handlers/containerd.yml
  tasks:
  - include: ./tasks/disks.yml
  - include: ./tasks/repositories.yml
    become: yes
  - include: ./tasks/packages.yml
  # - include: ./tasks/gsettings.yml
  - include: ../tasks/containerd.yml
    become: yes
  - name: Remove folders
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /home/rihards/Videos
      - /home/rihards/Templates
      - /home/rihards/Public
      - /home/rihards/Pictures
      - /home/rihards/Music
      - /home/rihards/Documents
