- name: Remove packages
  become: yes
  community.general.zypper:
    name: "{{ item }}"
    state: absent
  loop:
    - hexchat
    - rhythmbox
- name: Install packages
  become: yes
  community.general.zypper:
    name: "{{ item }}"
  loop:
    - vim
    - git
    - fish
    - chromium
    - audacious
    - sysstat
    - gimp
    - jq
    - keepassxc
    - cronie
    - gparted # To run, switch to root first
    # - lutris
    # - amdgpu_top
    # - libvulkan_radeon-32bit
    # - xf86-video-amdgpu
    # - dxvk
    # - libvkd3d1
    # - Mesa-libRusticlOpenCL
    # - wine

# - name: Update all packages
#   community.general.zypper:
#     name: '*'
#     state: latest
