- name: Remove packages
  become: yes
  community.general.zypper:
    name: "{{ item }}"
    state: absent
  loop:
    - hexchat
    - rhythmbox
- name: Install packages
  become: yes
  community.general.zypper:
    name: "{{ item }}"
  loop:
    - vim
    - git
    - fish
    - chromium
    - audacious
    - sysstat
    - gimp
    - jq
    - keepassxc
    - cronie
    - gparted
    - blueman
    - digikam
    - helm
    - btop # instead of psensor, though I should search more
    - audacity
