- name: Remove packages
  become: yes
  community.general.zypper:
    name: "{{ item }}"
    state: absent
  loop:
    - hexchat
    - rhythmbox
- name: Install packages
  become: yes
  community.general.zypper:
    name: "{{ item }}"
  loop:
    - vim
    - git
    - chromium
    - audacious
    - sysstat
    - gimp
    - jq
    - keepassxc
    - cronie
    - blueman
    # - psensor

- name: Update all packages
  community.general.zypper:
    name: '*'
    state: latest
