---
- name: Create app_user
  user:
    name: "{{ item }}"
    shell: /bin/bash
    generate_ssh_key: no
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{ item }}
  with_items: "{{ app_user }}"

- name: Copy SSH key
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '../Secrets/SSH_Keys/scaleway.pub') }}"
  with_items: "{{ app_user }}"

# - name: Install snapd for Ubuntu Live patch. Tried. Had error. Skipping it.
#   apt:
#     name: snapd
#     update_cache: yes

# Part that's to be executed by app_user
- block:
  - name: Copy ssh key for cloning
    copy:
      src: ../Secrets/SSH_Keys/ansible_for_clone
      dest: /home/{{ app_user }}/.ssh/id_rsa
      mode: 0600
  become: yes
  become_user: "{{ app_user }}"
