---
# Base setup - User setup,
- name: Make sure we have a 'code' group
  group:
    name: code
    state: present

- name: Allow 'code' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%code'
    line: '%code ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudoers users to code group
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: code
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{ item }}
  with_items: "{{ sudoers }}"

- name: Copy SSH key
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '../Secrets/SSH_Keys/scaleway.pub') }}"
  with_items: "{{ sudoers }}"

# Part that's to be executed by app_user
- block:
  - name: Copy ssh key for cloning
    copy:
      src: ../Secrets/SSH_Keys/ansible_for_clone
      dest: /home/{{ app_user }}/.ssh/ansible_for_clone
      mode: 0600
  become: yes
  become_user: "{{ app_user }}"
