---
- block:
  # Set up auth, clone repository
  - name: Copy ssh key for cloning
    copy:
      src: ../Secrets/SSH_Keys/for_clone
      dest: /home/{{ app_user }}/.ssh/for_clone # ansible_user is the user running ansible-playbook. So -u rihards
      mode: 0700

  - name: Create .docker directory
    file: path=/home/{{ app_user }}/.docker state=directory # Nice example of "single line"

  - name: Copy Docker auth
    copy:
      src: ../Secrets/Docker_auth.json
      dest: /home/{{ app_user }}/.docker/config.json
      mode: 0500

  - name: Clone/update the git repo
    git:
      repo: 'git@gitlab.com:RihardsT/cloud_project_infrastructure.git'
      dest: "{{ repo_path }}"
      depth: 1
      update: yes
      accept_hostkey: yes
      key_file: /home/{{ app_user }}/.ssh/for_clone

  become: yes
  become_user: "{{ app_user }}"