---
- block:
  - name: Pip install mkdocs and cinder theme
    pip:
      name: mkdocs,mkdocs-cinder
      state: latest
      executable: pip3

  # - name: Set permissions on {{ docs_path }}
  #   file: path={{ docs_path }} state=directory owner={{ app_user }} group={{ app_user }}
  # - name: Set permissions on {{ docs_path }}/site
  #   file: path={{ docs_path }} state=directory owner={{ app_user }} group={{ app_user }}
  become: yes
  become_user: root # This pip install requires root

- name: Clone/update the git repo
  git:
    repo: 'git@gitlab.com:RihardsT/cloud_project_documentation.git'
    dest: '{{ docs_repo_path }}'
    depth: 1
    update: yes
    accept_hostkey: yes
    key_file: /home/{{ app_user }}/.ssh/for_clone
    force: yes # TODO: Get rid of this by generating the site somewhere else
    # and updating nginx config to point to that.
    # Now this always complains about the folder existing...
  register: git # For the when: git.changed below

- name: Run mkdocs build
  command: mkdocs build --site-dir {{ docs_path }}/site
  args:
    chdir: '{{ docs_repo_path }}'
  when: git.changed # do this when new changes have pulled from git

- name: Restart Nginx service
  docker_service: # https://docs.ansible.com/ansible/docker_service_module.html
    project_src: "/srv/repo/DockerGunicorn/"
    files: docker-compose_{{ ansible_architecture }}.yml
    restarted: true
    state: present
    services: nginx
  when: git.changed # do this when new changes have pulled from git