---

- name: Pip install mkdocs and cinder theme
  pip:
    name: mkdocs,mkdocs-cinder
    state: latest
    executable: pip3
  become: yes
  become_user: root # This pip install requires root

- name: Set permissions on /var/www
  file: path=/var/www/ state=directory owner={{ app_user }} group={{ app_user }}

- name: Clone/update the git repo
  git:
    repo: 'git@gitlab.com:RihardsT/cloud_project_documentation.git'
    dest: '{{ repo_path }}'
    depth: 1
    update: yes
    accept_hostkey: yes
    key_file: /home/{{ app_user }}/.ssh/for_clone
  register: git # For the when: git.changed below

- name: Run mkdocs build
  command: mkdocs build
  args:
    chdir: '{{ docs_path }}'
  when: git.changed # do this when new changes have pulled from git

- name: Restart Nginx service
  docker_service: # https://docs.ansible.com/ansible/docker_service_module.html
    project_src: "/srv/repo/DockerGunicornARM/"
    restarted: true
    state: present
    services: nginx
  when: git.changed # do this when new changes have pulled from git